create LoginPage, complete design and navigation to RegisterPage
Muhammed58/EcommerceLesson pull request #3
Opened 2023-09-24 03:21 UTC by devhakanozdemir

LoginPage created. Design completed and navigation link to RegisterPage is ready.

2023-09-25 17:14 UTC, Muhammed58 commented on src/screens/LoginPage.js
> +  }
```suggestion
  const HandleOnPress = () => {
    console.log({email, password})
  }
```

Bu bölümü düzeltmen gerekli

2023-09-25 17:36 UTC, Muhammed58 commented on src/screens/LoginPage.js
> +  },
```suggestion
  mainContainer: {
    justifyContent: "center",
    alignItems: "center",
    flex:1
  },
```

2023-09-25 17:37 UTC, Muhammed58 requested changes
Kodlardaki yorum satırında belirtilen değişiklikleri yapmalısınız.

2023-09-27 11:05 UTC, devhakanozdemir commented
hatali kisimlar duzeltilerek tekrar push edildi

2023-09-27 14:56 UTC, Muhammed58 approved these changes
Tebrikler tüm kodlar sorunsuz çalışıyor

2023-09-27 14:56 UTC, merged